service: home-linting

plugins:
  - serverless-finch
  - serverless-build-client

custom:
  clientName: home
  bucketName: ${self:custom.clientName}-pr-reports
  auth: ${file(./env.yml):auths}
  GITHUB_WEBHOOK_SECRET: ${file(./env.yml):GITHUB_WEBHOOK_SECRET}
  GITHUB_API_TOKEN: ${file(./env.yml):GITHUB_API_TOKEN}
  # This is for finch the static site generator
  client:
    bucketName: ${self:custom.bucketName}
    distributionFolder: './frontend/build'

package:
  individually: true
  exclude:
    - "frontend/node_modules/**"

provider:
  name: aws
  timeout: 30
  runtime: nodejs10.x
  region: eu-west-1
  profile: HOME-TOOLS
  role: arn:aws:iam::547637678216:role/RC-Git-deployment
  #excludeDevDependencies: false
  environment:
    bucket: ${self:custom.bucketName}
    clientName: ${self:custom.clientName}
    reportUrl: https://qqiyzb9w1d.execute-api.eu-west-1.amazonaws.com/dev
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        - { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ]]}
        - arn:aws:s3:::${self:custom.bucketName}/*

functions:

  GithubPRLint--RC:
    handler: dist/init.handler
    package:
      individually: true
      exclude:
        - "src"
        - "frontend"
      include:
        - "dist"
    environment:
      auth: ${self:custom.auth} # This passes the values stored in you .env file into your lambda function.
      GITHUB_WEBHOOK_SECRET: ${self:custom.GITHUB_WEBHOOK_SECRET}
      BUCKET: ${self:custom.bucketName}
      GITHUB_API_TOKEN: ${self:custom.GITHUB_API_TOKEN}
      HOME: '/tmp'
    name: GithubPRLint
    description: Lambda function used lint Pull Requests.
    tags:
      client: royal canin
      application: lambda
      project: design language
    events:
      - http:
          path: /githooks
          method: post
          cors: true

  reportFetcher--RC:
    handler: dist/reportFetcher.handler
    package:
      individually: true
      exclude:
        - "src"
        - "dist"
        - "frontend/*"
      include:
        - "frontend/build"
    environment:
      auth: ${self:custom.auth} # This passes the values stored in you .env file into your lambda function.
      BUCKET: ${self:custom.bucketName}
    name: reportFetcher
    description: Lambda function used to fetch reports generated from linting Pull Requests.
    tags:
      client: royal canin
      application: lambda
      project: design language
    events:
      - http:
          path: /reports/get
          method: post
          cors: true

resources:
  Resources:
    ReportBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}

Outputs:
  AttachmentsBucketName:
    Value:
      Ref: ReportBucket

